#!/bin/bash

file=$1 ; [[ -z $file ]] && file="/lib/firmware/wrt/uImageDtb.bin"
cur_boot_part=`fw_printenv -n boot_part`
#cur_boot_part="2"
echo "Current boot_part" $cur_boot_part
if [ -r "$file" ]; then
  if [ "$cur_boot_part" = "2" ]; then
    bp=1 ; mt="/dev/mtd5" ; bc="run nandboot"
  elif [ "$cur_boot_part" = "1" ]; then
    bp=2 ; mt="/dev/mtd7" ; bc="run altnandboot"
  else
    echo "Error reading boot_part..." ; exit
  fi
else
  echo "File not found..." ; exit
fi

echo "Are you sure you want to write "$file" to boot_part "$bp" at "$mt" ???" 
read -p "Type <yes> to confirm: " prompt
[[ ! $prompt == "yes" ]] && exit

#exit

fw_setenv auto_recovery yes
flash_erase $mt 0 0
nandwrite -p $mt $file
#fw_setenv bootcmd $bc
fw_setenv boot_part $bp
fw_setenv boot_part_ready 3



