#!/bin/bash

function fwsetenv { v="${@:2}"; if [ "$(fw_printenv -n $1)" != "$v" ]; then fw_setenv "$@"; fi }

modelstr=$(expr substr $(strings /dev/mtd3 | grep 'modelNumber=') 13 20)
case $modelstr in 
  WRT3200ACM*) model="rango"  ;;
  WRT1900ACS*) model="shelby" ;;
  *) echo "Unknown model" ; exit ;;
esac
echo $modelstr" , name="$model

cur_boot_part=$(fw_printenv -n boot_part)
echo "Current boot_part" $cur_boot_part
case $cur_boot_part in
  2) bp=1 ;;
  1) bp=2 ;;
  *) echo "Error reading boot_part..." ; exit ;;
esac 
mt=$(echo $(cat /proc/mtd | grep kernel$bp) | cut -d : -f 1)

echo Last written file:
cat /lib/firmware/wrt/kernel""$bp""lastwritten

ffile=$@ ;
if  [ -z $ffile ]; then
  echo Choose from the following files:
  options=( $(find /lib/firmware/wrt/*-$model-*.bin -maxdepth 0 -print0 -type f | xargs -0) )
  PS3="Please select a file: "
  select ffile in "${options[@]}" "Quit" ; do
    if (( REPLY > 0 && REPLY <= ${#options[@]} )) ; then
      break
    else exit
    fi
  done    
fi

if [ ! -r "$ffile" ]; then echo "ffile not found..." ; exit ; fi


echo "Are you sure you want to write "$ffile" to boot_part "$bp" at "$mt" ???" 
read -p "Type <yes> to confirm: " prompt
[[ ! $prompt == "yes" ]] && exit

echo $ffile >/lib/firmware/wrt/kernel""$bp""lastwritten

fwsetenv auto_recovery yes
flash_erase /dev/$mt 0 0
nandwrite -p /dev/$mt $ffile
fwsetenv boot_part $bp
fwsetenv boot_part_ready 3

exit

