#!/bin/bash

function fwsetenv { v="${@:2}"; if [ "$(fw_printenv -n $1)" != "$v" ]; then fw_setenv "$@"; fi }

modelstr=$(expr substr $(strings /dev/mtd3 | grep 'modelNumber=') 13 20)
case $modelstr in 
  WRT3200ACM*) model="rango"  ;;
  WRT1900ACS*) model="shelby" ;;
  *) echo "Unknown model" ; exit ;;
esac
echo $modelstr" , name="$model

file=$@ ; [[ -z $file ]] && file="/lib/firmware/wrt/uImageDtb-"$model".bin"
if [ ! -r "$file" ]; then echo "File not found..." ; exit ; fi

cur_boot_part=$(fw_printenv -n boot_part)
echo "Current boot_part" $cur_boot_part
case $cur_boot_part in
  2) bp=1 ;;
  1) bp=2 ;;
  *) echo "Error reading boot_part..." ; exit ;;
esac 

mt=$(echo $(cat /proc/mtd | grep kernel$bp) | cut -d : -f 1)

echo "Are you sure you want to write "$file" to boot_part "$bp" at "$mt" ???" 
read -p "Type <yes> to confirm: " prompt
[[ ! $prompt == "yes" ]] && exit

fwsetenv auto_recovery yes
flash_erase $mt 0 0
nandwrite -p $mt $file
fwsetenv boot_part $bp
fwsetenv boot_part_ready 3

exit




