#!/bin/bash

#gcc=""   # use standard ubuntu gcc version
gcc="https://launchpad.net/gcc-arm-embedded/4.9/4.9-2015-q3-update/+download/gcc-arm-none-eabi-4_9-2015q3-20150921-linux.tar.bz2"
#gcc="https://developer.arm.com/-/media/Files/downloads/gnu-rm/8-2019q3/RC1.1/gcc-arm-none-eabi-8-2019-q3-update-linux.tar.bz2"

#mainline="http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.14.13"
mainline="http://kernel.ubuntu.com/~kernel-ppa/mainline/v5.4.69"
kernellocalversion="-wrt0"           # Is added to kernelversion by make for name of modules dir.

models="rango shelby" # caiman cobra # Model names in arch/arm/boot/dts/armada-385-linksys-xxx.dts

#release="xenial"                    # Ubuntu version
release="focal"                      # Ubuntu version
neededpackages="locales,hostapd,u-boot-tools,mtd-utils,openssh-server,crda,resolvconf,iproute2,nftables"
extrapackages="vim,dbus,screen"      # Extra packages installed in rootfs, comma separated list, no spaces

wubuntu="WUBUNTU"                    # Label usb-disk for installation
mbrid="abcdefba"                     # Change usb mbr id (partuuid) to this value when options are -uU 
lc="en_US.UTF-8"                     # Locale
timezone="Europe/Paris"              # Timezone
keyboard="us"                        # Keyboard
rootpwd="admin"                      # Root password

function finish {
  echo Running exit function to clean up...
  if [ "$u" = true ] ; then
    while mountpoint -q $rootfsdir; do
      $sudo umount $rootfsdir
      sleep 0.1
    done    
    $sudo rm -rf $rootfsdir
  fi
}

exec > >(tee -i build.log)
exec 2> >(tee build-error.log)

# INIT VARIABLES
[ $USER = "root" ] && sudo="" || sudo="sudo"
[[ $# == 0 ]] && args="-rktua"|| args=$@
echo "build "$args
cd $(dirname $0)
while getopts ":rktuaRKTU" opt $args; do declare "${opt}=true" ; done
trap finish EXIT
$sudo true
shopt -s extglob
if [ -z $(cat /proc/cpuinfo | grep Hardware.*Armada.*380/385) ]; then
  echo "Not running on Armada CPU"
  makej="-j4"
  if [ "$u" = true ] && [ ! -z $(blkid -L $wubuntu) ]; then
    rootfsdir=/media/$wubuntu
    $sudo umount $(blkid -L $wubuntu)
    if [ "$U" = true ] ; then
      dev=/dev/$(lsblk -no pkname $(blkid -L $wubuntu))
      getid=$(echo $($sudo dd if=$dev bs=1 count=4 skip=440 2>/dev/null | od -t x4 -An))
      if [[ $(lsblk -no partuuid $dev) = *$getid* ]]; then
        echo "Are you sure you want to write "$mbrid" to MBR ID at "$dev" ???" 
        read -p "Type <yes> to confirm: " prompt; 
        if [[ $prompt == "yes" ]]; then
          echo -en "\x${mbrid:6:2}\x${mbrid:4:2}\x${mbrid:2:2}\x${mbrid:0:2}" | \
            $sudo dd of=$dev bs=1 count=4 seek=440
        fi
      else
        echo "Error reading MBR ID, not going to write MBR ID! (Maybe GPT?)"
        exit
      fi
    fi
    $sudo mkdir $rootfsdir
    $sudo mount --source LABEL=$wubuntu $rootfsdir -o exec,dev
  else
    rootfsdir="rootfs-"$release ; u=""
  fi
else
  echo "Running on Armada CPU"
  makej="-j1" # make with one core on WRT to try not overheating cpu
  rootfsdir="" ; r="" ; R="" ; u=""
fi

if [ -z $gcc ]; then
  gccpath=""
else
  gccpath=$(realpath $(find gcc -wholename */bin/arm-none-eabi-gcc))
  if [ ${#gccpath} -ge 17 ]; then gccpath=${gccpath:0:-17}
  else 
    echo Install the desired gcc first with option -a.
    exit""
  fi
fi
crossc="CROSS_COMPILE="$gccpath"arm-none-eabi-" 
kernelversion=$(basename $mainline)
schroot="$sudo LC_ALL=C LANGUAGE=C LANG=C chroot $rootfsdir"
kerneldir=$rootfsdir/usr/src/linux-headers-$kernelversion
echo INSTALLDIR: $rootfsdir
echo OPTIONS: rootfs=$r kernel=$k tar=$t usb=$u apt=$a 
if [ "$K" = true ] ; then
  echo Removing kernelsource...
  $sudo rm -rf $kerneldir
fi
if [ "$R" = true ] ; then
  echo Removing rootfs...
  $sudo rm -rf $rootfsdir
fi
if [ "$T" = true ] ; then
  echo Removing .tar...
  rm -f rootfs-$release.tar.bz2 kernel-$kernelversion.tar.gz modules-$kernelversion$kernellocalversion.tar.gz
fi
if [ "$a" = true ]; then
  $sudo apt-get install --yes build-essential flex bison gcc-arm-none-eabi u-boot-tools libncurses-dev
  if [ -z $rootfsdir ]; then
    $sudo apt-get install --yes wget bc ca-certificates  # install these when running on WRT
  else
    $sudo apt-get install --yes debootstrap qemu-user-static libc6:i386 gcc-arm-linux-gnueabihf
    gccname=$(basename $gcc)
    wget -nv -N $gcc
    rm -rf gcc
    mkdir gcc
    tar -xjf $gccname -C gcc  
  fi
fi

### ROOTFS ###
if [ "$r" = true ]; then
  [ ! -z $rootfsdir ] && $sudo mkdir $rootfsdir
  if [ ! -d "$rootfsdir/sbin" ]; then
    if [ ! -f "rootfs-$release.tar.bz2" ]; then
      packages=$neededpackages","$extrapackages
      [[ -f "custom/rootfs-$release/etc/network/interfaces" ]] && packages="$packages,ifupdown"
      $sudo debootstrap --arch=armhf --foreign --no-check-gpg --components=main,restricted,universe,multiverse \
        --include="$packages" $release $rootfsdir "http://ports.ubuntu.com/ubuntu-ports"
      $sudo cp /usr/bin/qemu-arm-static $rootfsdir/usr/bin/
      $schroot /debootstrap/debootstrap --second-stage
      if [ "$t" = true ]; then
        echo "Creating rootfs.tar..."
        $sudo tar -cjf rootfs-$release.tar.bz2 -C $rootfsdir .
        $sudo chown -R $USER:$USER rootfs-$release.tar.bz2
      fi
    else
      echo "Extracting rootfs.tar..."
      $sudo tar -xjf rootfs-$release.tar.bz2 -C $rootfsdir
    fi
  fi
  $schroot locale-gen $lc
  $schroot update-locale LANGUAGE=$lc LC_ALL=$lc LANG=$lc
  #LC_PAPER=$lc LC_ADDRESS=$lc LC_MONETARY=$lc LC_NUMERIC=$lc LC_TELEPHONE=$lc LC_IDENTIFICATION=$lc LC_MEASUREMENT=$lc LC_TIME=$lc LC_NAME=$lc
  $schroot ln -sf /usr/share/zoneinfo/${timezone} /etc/localtime
  $schroot sed -i 's/XKBLAYOUT=\"us\"/XKBLAYOUT=\"${keyboard}\"/g' /etc/default/keyboard
  echo root:$rootpwd | $schroot chpasswd 
  $sudo cp -r --remove-destination -v custom/rootfs-$release/. $rootfsdir
  for nr in $rootfsdir/bash.* ; do source $nr                                             ; $sudo rm -rf $nr ; done
  for nr in $rootfsdir/patch.*; do echo $nr ; $sudo patch -d $rootfsdir -p1 -N -r - < $nr ; $sudo rm -rf $nr ; done
  [[ -d "custom/rootfs-$release/etc/systemd/network" ]] && $schroot systemctl reenable systemd-networkd.service
  find "custom/rootfs-$release/etc/systemd/system" -name "*.service"| while read service ; do
    $schroot systemctl reenable $(basename $service) # enable all custom services
  done
  $schroot systemctl daemon-reload
  $sudo mkdir -p $rootfsdir/root/buildWubuntu
  $sudo cp -rfv custom $rootfsdir/root/buildWubuntu/custom
  $sudo cp -fv build $rootfsdir/root/buildWubuntu/build
  $sudo make --directory=$rootfsdir/root/buildWubuntu/custom/tools clean linksys_bootcount_cross
  if [ "$k" != true ] && [ -f "modules-$kernelversion$kernellocalversion.tar.gz" ]; then
    echo "Not compiling kernel, adding modules and firmware from .tar..."
    $sudo tar -xzf modules-$kernelversion$kernellocalversion.tar.gz -C $rootfsdir
  fi
fi

### KERNEL ###
if [ "$k" = true ] ; then
  $sudo mkdir $rootfsdir
  if [ ! -d "$kerneldir" ]; then
    if [ ! -f "kernel-$kernelversion.tar.gz" ]; then
      gitbranch=$(wget -nv -qO- $mainline/HEADER.html | grep -m 1 git://)
      gitbranch=${gitbranch//&nbsp;/}
      gitbranch=(${gitbranch//<br>/})
      $sudo git clone --branch ${gitbranch[1]} --depth 1 ${gitbranch[0]} $kerneldir
      $sudo rm -rf $kerneldir/.git
      sources=$(wget -nv -qO- $mainline/SOURCES) ; readarray -t sources <<<"$sources"
      if [ ! -z "${sources[0]}" ]; then # has SOURCES file
        src=1
        while [ $src -lt ${#sources[@]} ]; do
          wget -nv -O /dev/stdout $mainline"/"${sources[$src]} | $sudo patch -d $kerneldir -p1
          let src++
        done
      fi
      if [ "$t" = true ]; then
        echo "Creating kernel.tar..."
        tar -czf kernel-$kernelversion.tar.gz -C $kerneldir .
      fi
    else
      $sudo mkdir -p $kerneldir
      echo "Extracting kernel.tar..."
      $sudo tar -xzf kernel-$kernelversion.tar.gz -C $kerneldir
    fi
  fi
  makeoptions="--directory="$kerneldir" LOCALVERSION="$kernellocalversion" DEFAULT_HOSTNAME=WUBUNTUTEST ARCH=arm "$crossc" KBUILD_BUILD_TIMESTAMP=1/1/2011 KBUILD_BUILD_VERSION=123"
  $sudo mkdir -p $rootfsdir/lib/firmware/wrt
  $sudo cp -r --remove-destination -v custom/kernel-$kernelversion/. $kerneldir
  $sudo cp -r --remove-destination -v custom/rootfs-$release/lib/firmware/. $rootfsdir/lib/firmware/
  $sudo cp --remove-destination -v $kerneldir/arch/arm/configs/mvebu_v7_defconfig $kerneldir/arch/arm/configs/wubuntu_defconfig
  $sudo bash -c "cat               $kerneldir/diff_defconfig                    >>$kerneldir/arch/arm/configs/wubuntu_defconfig"
  $sudo make $makeoptions wubuntu_defconfig
  $sudo cp --remove-destination -v $kerneldir/.config $kerneldir/before.config
  for nr in $kerneldir/bash.* ; do source $nr                                             ; $sudo rm -rf $nr ; done
  for nr in $kerneldir/patch.*; do echo $nr ; $sudo patch -d $kerneldir -p1 -N -r - < $nr ; $sudo rm -rf $nr ; done
  $sudo make $makeoptions KCONFIG_ALLCONFIG=.config allnoconfig # only add config entries added in patch.diff or bash.script
  #$sudo make $makeoptions menuconfig
  diff -Naur  $kerneldir/before.config $kerneldir/.config >config-changes.diff
  $sudo rm -f $kerneldir/before.config
  $sudo make $makeoptions $makej zImage modules
  $sudo make $makeoptions modules_install INSTALL_MOD_PATH="../../.."
  kernelrelease=$($sudo make -s $makeoptions kernelrelease)
  $sudo depmod -ab $rootfsdir/. $kernelrelease
  $sudo ln --force --symbolic --relative --no-dereference $kerneldir $rootfsdir/lib/modules/$kernelrelease/build
  $sudo ln --force --symbolic --relative --no-dereference $kerneldir $rootfsdir/lib/modules/$kernelrelease/source
  md5str=$(openssl dgst -r -md5 $kerneldir/vmlinux); md5str=${md5str: 0: 8} # only changes with vmlinux changes
  for model in $models 
  do
    $sudo make $makeoptions $makej armada-385-linksys-$model.dtb
    cp --remove-destination -v $kerneldir/arch/arm/boot/zImage zImageDtb-$model
    cat $kerneldir/arch/arm/boot/dts/armada-385-linksys-$model.dtb >> zImageDtb-$model
    mkimage -A arm -O linux -T kernel -C none -a 0x200000 -e 0x200000 -n linux -d zImageDtb-$model uImageDtb-$model.bin
    rm -f zImageDtb-$model
    $sudo cp --remove-destination -v uImageDtb-$model.bin \
             $rootfsdir/lib/firmware/wrt/uImageDtb-$model-$kernelversion$kernellocalversion-$md5str.bin
  done
  if [ "$t" = true ]; then
    echo "Creating modules.tar..."
    tar -czf modules-$kernelversion$kernellocalversion.tar.gz -C $rootfsdir/. ./lib/modules/$kernelrelease ./lib/firmware
  fi
  
fi

exit

