#!/bin/bash

case $IFACE in 
  br0)   ifup -v eth1 eth0 lan1 lan2 lan3 lan4 wan ; exit 0 ;;
  eth0)   nr=0 ;;
  wlp2s0) nr=1 ;;
  wlp1s0) nr=2 ;;
  mlan0)  nr=3 ;;
  lan1)   nr=0 ;;
  lan2)   nr=0 ;;
  lan3)   nr=0 ;;
  lan4)   nr=0 ;;
  eth1)   nr=0 ;;
  wan)    nr=0 ;;
  *) exit 0 ;;
esac
mac=`strings /dev/mtd3 | grep hw_mac_addr | cut -d= -f2`
ip link set $IFACE address ${mac::-2}$(printf '%02X\n' $(($(($((16#${mac: -2}))+$nr))&255)))
exit 0





