#!/bin/bash

case $IFACE in 
  br0)   ifup -v eth1 lan1 lan2 lan3 lan4 wan ; exit 0 ;;
# eth0)   nr=0 ;;
# wlp2s0) nr=1 ;;
# wlp2s0) nr=2 ;;
# mlan0)  nr=3 ;;
  lan1)   nr=4 ;;
  lan2)   nr=5 ;;
  lan3)   nr=6 ;;
  lan4)   nr=7 ;;
  eth1)   nr=8 ;;
  wan)    nr=9 ;;
  *) exit 0 ;;
esac
mac=`strings /dev/mtd3 | grep hw_mac_addr | cut -d= -f2`
ip link set $IFACE address ${mac::-2}$(printf '%02X\n' $(($(($((16#${mac: -2}))+$nr))&255)))
exit 0





